name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Capturar versão da tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Criar arquivo ZIP com versão
        run: |
          zip -r page-flipper-${VERSION}.zip . \
          -x ".git/*" ".github/*" "LICENSE" "README.md"

      - name: Criar Release e anexar ZIP
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          files: page-flipper-${{ env.VERSION }}.zip
