name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Capture tag version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Copy license to wordpress version
        run: cp LICENSE ./license.txt

      - name: Create ZIP file
        run: |
          zip -r page-flipper-${VERSION}.zip . \
          -x ".git/*" ".github/*" "README.md" "LICENSE" "assets/banner.png"

      - name: Create release and attach ZIP
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          files: page-flipper-${{ env.VERSION }}.zip
